- hosts: all
  become: true
  vars:
    aws_s3_bucket: "web-server-content-23-08-19"
    aws_s3_object: "index.html"
    
  tasks:
    - name: Install Nginx & packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - nginx
          - awscli
          - python-pip

    - name: Install pip Ansible dependencies
      pip: 
        name: 
          - botocore 
          - boto3

    - name: Remove default template
      file: 
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Upload web server config
      template:  
        src: templates/web-site.j2
        dest: "/etc/nginx/sites-enabled/web-site.conf"

    - name: Restart and enable Nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Upload s3 index.html 
      aws_s3:      
        bucket: "{{ aws_s3_bucket }}"
        object: "{{ aws_s3_object }}"
        dest: /var/www/html/index.html
        mode: get

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
        
    - name: Add crontab task to get index.html after boot
      cron:
        name: "Dowload index.html file at reboot"
        cron_file: s3-tasks
        user: root
        special_time: reboot
        job: "/usr/bin/aws s3 cp s3://{{ aws_s3_bucket }}/{{ aws_s3_object }} /var/www/html/index.html"

